### ISSUE TITLE
any way to get 1:1 pixel boundary → vector mapping?

### ISSUE THREAD

**Issue by scruss** [mzucker/maptrace#4]
In short, I'm looking for a command-line equivalent of Glimpse / Gnu IMP's* selection to path to trace bitmaps like this:

https://1.bp.blogspot.com/-T5CpzjCoSfM/Xg2ZJWK8k2I/AAAAAAAAIlI/tezuJjWcXugphtQiMFitS5wGD5pe_dLVwCLcBGAsYHQ/s1600/eicar.png

but things do not go well

*: I won't use their ableist name.

**Comment by mzucker** [comment]
Was gonna write a whole big comment about how that's not the intended use case of the tool blah blah but then just went ahead and implemented a mode for this. Pull 7e259be and run with the -S flag. (Also updated to Python 3 cause Python 2 is now deprecated). Here's the SVG output, converted to PNG:

![eicar_bw](https://user-images.githubusercontent.com/3287580/94074733-e6293180-fdc7-11ea-958f-7ae6608deb31.png)

Here's what happens when you run with the -r flag:

![eicar_random_colors](https://user-images.githubusercontent.com/3287580/94074773-f2ad8a00-fdc7-11ea-9abd-7d3381fbcd7d.png)

Don't know why you didn't like the original output, it looks great to me:

![eicar_silly](https://user-images.githubusercontent.com/3287580/94074885-212b6500-fdc8-11ea-816e-b3af0dc3696b.png)

Guess there's no accounting for taste.
